# arguments for dataset
dataset: ade20k
data_root: data/ADE20K/ADEChallengeData2016  # path to ADE20K 
nclass: 150
crop_size: 640
patch_size: 16
align_corners: False

# arguments for training
epochs: 60
eval_epoch: 1
batch_size: 4 # per GPU x 2 GPUs
lr: 0.000005
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: mask2former
backbone: dinov3_large
lock_backbone: False
