# arguments for dataset
dataset: cityscapes
data_root: data/cityscapes/  # path to Cityscapes
nclass: 19
crop_size: 798
patch_size: 14
align_corners: False

# arguments for training
epochs: 180
eval_epoch: 1
batch_size: 8 # per GPU
lr: 0.000005 
lr_multi: 40.0 
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_small 
# backbone: dinov2_base
lock_backbone: False 
