# arguments for dataset
dataset: coco
data_root: data/coco  # path to COCO
nclass: 81
crop_size: 518
patch_size: 14
align_corners: False

# arguments for training
epochs: 20
batch_size: 16 # per GPU
lr: 0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_small
# backbone: dinov2_base
lock_backbone: False
